FROM openjdk:latest
LABEL authors="Vika"
LABEL version="1.0"
LABEL description="This is a docker image for my java project"
LABEL maintainer="Vika"
COPY . /tmp
WORKDIR /tmp
ENTRYPOINT ["java","Main"]
